name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us investigate.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Initialize tensor with...
        2. Call function...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened instead.
      placeholder: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Ubuntu 22.04
        - Ubuntu 20.04
        - Ubuntu 18.04
        - CentOS 7/8
        - RHEL 7/8
        - Windows 10
        - Windows 11
        - macOS
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: cuda-version
    attributes:
      label: CUDA Version
      description: What version of CUDA are you using?
      options:
        - CUDA 12.4
        - CUDA 12.3
        - CUDA 12.2
        - CUDA 12.1
        - CUDA 12.0
        - CUDA 11.8
        - CUDA 11.7
        - CUDA 11.6
        - CUDA 11.5
        - CUDA 11.4
        - CUDA 11.3
        - CUDA 11.2
        - CUDA 11.1
        - CUDA 11.0
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: gpu
    attributes:
      label: GPU Model
      description: What GPU are you using?
      placeholder: e.g., NVIDIA RTX 4090, A100, V100
    validations:
      required: true

  - type: input
    id: driver
    attributes:
      label: NVIDIA Driver Version
      description: What NVIDIA driver version are you using?
      placeholder: e.g., 535.104.05

  - type: input
    id: compiler
    attributes:
      label: Compiler Version
      description: What compiler are you using?
      placeholder: e.g., GCC 11.4.0, Clang 15.0

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs.
      render: shell

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: If possible, provide a minimal code example that reproduces the issue.
      render: cpp

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
