name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!
        Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case or problem this feature would solve.
      placeholder: |
        As a [type of user], I want [goal] so that [benefit].
        
        Example: As a deep learning researcher, I want optimized sparse attention kernels so that I can train large language models more efficiently.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: If you have ideas on how this could be implemented, please share them.
      placeholder: Describe your proposed solution...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternatives you've considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall under?
      options:
        - New Kernel (GEMM, Attention, etc.)
        - Performance Optimization
        - Memory Management
        - API Enhancement
        - Python Bindings
        - Documentation
        - Build System
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Important
        - Critical for my use case

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, references, or screenshots about the feature request.
